"""empty message

Revision ID: 106d59880467
Revises: 8e4a069b4510
Create Date: 2018-06-25 16:11:06.715304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106d59880467'
down_revision = '8e4a069b4510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('user_cpf', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ads', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'ads', 'users', ['user_cpf'], ['cpfuser'])
    op.add_column('interests', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('interests', sa.Column('user_cpf', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interests', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'interests', 'users', ['user_cpf'], ['cpfuser'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interests', type_='foreignkey')
    op.drop_constraint(None, 'interests', type_='foreignkey')
    op.drop_column('interests', 'user_cpf')
    op.drop_column('interests', 'book_id')
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_column('ads', 'user_cpf')
    op.drop_column('ads', 'book_id')
    # ### end Alembic commands ###
