"""empty message

Revision ID: 8e4a069b4510
Revises: 
Create Date: 2018-06-25 15:19:09.949394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4a069b4510'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('cpfuser', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pw_hash', sa.String(length=80), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=True),
    sa.Column('dtbirth', sa.Date(), nullable=True),
    sa.Column('grant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cpfuser'),
    sa.UniqueConstraint('email')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=False),
    sa.Column('serie', sa.String(length=80), nullable=False),
    sa.Column('school', sa.String(length=80), nullable=False),
    sa.Column('edition', sa.String(length=80), nullable=False),
    sa.Column('translateversion', sa.String(length=80), nullable=True),
    sa.Column('phisicalstate', sa.Text(), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('user_cpf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_cpf'], ['users.cpfuser'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('interests')
    op.drop_table('ads')
    # ### end Alembic commands ###
